# Generated by Django 4.0.6 on 2022-07-27 20:17

import django
from django.db import migrations, models


def insert_group_id(apps, schema_editor):

    File = apps.get_model('data_loader', 'File')
    for file in File.objects.all():
        file.group.id = None
        file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0004_filegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='File',
            name='group',
            field=models.ForeignKey(on_delete=models.SET_NULL,
                                    null=True, blank=True, default=None, to='data_loader.filegroup'),
            preserve_default=False
        ),
        # migrations.RunPython(insert_group_id),
    ]
