# Generated by Django 4.0.6 on 2022-07-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0006_insertion_name_specialinsertion_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insertion',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='specialinsertion',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='externsystem',
            name='system_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
