# Generated by Django 4.0.6 on 2022-08-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0008_alter_externsystem_options_groupinsertion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupinsertion',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.FileField(default='', upload_to='files'),
        ),
    ]
